services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: project_yellow_taxi_etl_pipeline
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data_project:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

